Repository dataware-tools/api-permission-manager, pull requests merged in 2021-07, with the labels that each got.

#35 Use GitHub-hosted runners
  .github/workflows/build_and_test.yml
Labels: approved

#34 Fix README
  README.md
Labels: approved, lgtm, size/XS

#36 Add ids of permitted databases to returns
  aerich.ini
  api/models.py
  api/schemas.py
  api/server.py
  poetry.lock
  pyproject.toml
  test/test_api/test_permitted_databases.py
  test/test_models.py
Labels: approved, lgtm, size/XL
